version: 1

prefix:
  name: 'EnderCarryOn'
  color: '#6400d4'
  useArrow: true

resource_pack:
  use: true
  url: "https://github.com/Endkind/EnderCarryOn/releases/download/v0.0.1/resourcepack.zip"
  hash: "{hash_resourcepack}"  # A 40 character hexadecimal and lowercase SHA-1 digest of the resource pack file.
