version: 2

prefix:
  name: 'EnderCarryOn'
  color: '#6400d4'
  useArrow: true

resource_pack:
  use: true
  url: "https://github.com/Endkind/EnderCarryOn/releases/download/{tag}/resourcepack.zip"
  hash: "{hash_resourcepack}"  # A 40 character hexadecimal and lowercase SHA-1 digest of the resource pack file.

reset_walk_speed_on_join: false  # Only required when upgrading from v0.0.1 to a higher version if players experience constant slow movement issues.
